### ISSUE TITLE
Use original stylegan generator

### ISSUE THREAD

**Issue by raywzy** [SeanChenxy/Mimic3D#2]
Thanks for the awesome work!

One small question: Is there any convenient way to use the original stylegan generator to generate triplanes? i.e. The experiments of Table 3 second row.

**Comment by SeanChenxy** [comment]
Hi, you can try to set `aware3d_res: []` in the config file.

**Comment by raywzy** [comment]
Thanks a lot!

Some other small questions:

1. is there any difference between your lpips and the pip's one?
2. I found finetuning 3D stage will easily lead to OOM once the evaluation starts, are there any ways to avoid that?

**Comment by SeanChenxy** [comment]
Hi, 
1. While I have not compared our LPIPS metric with the one from pip, they should theoretically align when using the VGG network.
2. To prevent OOM, you can decrease the value of `chunk` in the configuration file.

**Comment by raywzy** [comment]
Thanks! I have followed your instructions and set `aware3d_res: [] `, but seems there is no 3D SR model? Do I need to set the `add_sr_module` to be true as well?
