### ISSUE TITLE
is there any weight for ffhq dataset with triplane_act=tanh

### ISSUE THREAD

**Issue by diamond0910** [SeanChenxy/Mimic3D#3]
nice work ! is there any weight for ffhq dataset with triplane_act=tanh?

**Comment by SeanChenxy** [comment]
Hi, this configuration did not yield satisfactory results in our experiments.

**Comment by diamond0910** [comment]
thank you for your reply. What do satisfactory results mean? FID not low enough? Is 3D consistency not good enough? Or does the training not converge?
