### ISSUE TITLE
is there any weight for ffhq dataset with triplane_act=tanh

### ISSUE THREAD

**Issue by diamond0910** [SeanChenxy/Mimic3D#4]
Thank you for your reply. What do satisfactory results mean? FID not low enough? Is 3D consistency not good enough? Or does the training not converge?

**Comment by SeanChenxy** [comment]
Hi, in our experiments, the training fail to converge, and we find this problem is caused by `Greg` loss.

**Comment by zhouwy19** [comment]
How to explain how Greg affects convergence? In addition, I train the EG3D using tanh function to activate the triplanes. I think it can be restrained, but the face seems to be separated from the hair. Have you had any experience？Thank you for your reply.

Uploading 279_1694072055_raw.mp4…

**Comment by diamond0910** [comment]
How to explain how Greg affects convergence? In addition, I train the EG3D using tanh function to activate the triplanes. I think it can be restrained, but the face seems to be separated from the hair. Have you had any experience？Thank you for your reply.

https://github.com/SeanChenxy/Mimic3D/assets/43036573/03fb8b4f-9f6e-4133-bb04-65222fa792e3

**Comment by SeanChenxy** [comment]
`Greg` actually works for geometry smooth. Hence, increasing `Greg` could relieve this error, but at the same time impact the image quality. In my opinion,`tanh` could reduce the variance of planes, and `Greg` is more easy to produce over-smooth geometry, making training failure at early stage. I am not very confident about my thought. More experiments are necessary.

**Comment by diamond0910** [comment]
Thank you for your reply. I check the values. To my surprise, the Greg loss is just 0.0014, even though the geometry displayed in the video is so poor. The Gmain loss is around 3. It seems that the design of Greg is not conducive to ensuring a good geometry.

**Comment by SeanChenxy** [comment]
This is a tradeoff because FID value will incearse if you enhance Greg loss.

**Comment by diamond0910** [comment]
Thank you for your reply and discussion. I tried to set the coefficient of G_reg to 100 to increase the geometric constraint, but there was still a floating face situation in the video. It seems like this is a very confusing question.
