### ISSUE TITLE
Official weights and 3D SR module

### ISSUE THREAD

**Issue by JiuTongBro** [SeanChenxy/Mimic3D#8]
Hi! Thanks for your impressive work.

However, I noticed that, to use the 3D SR module, we seems need to set the `add_sr_module` to `True`. But in your 3d config files, they are set to `False`. So I wonder, does the model of your official weights set the `add_sr_module` to `True`? In other words, does your official weights contain the 3D SR module?

Thanks.

**Comment by SeanChenxy** [comment]
Hi, `add_sr_module` is deprecated. Instead, `add_3dblock` is used to control feature super-resolution.

**Comment by JiuTongBro** [comment]
Hi, thanks. But I didn't found this option in the config files, nor in the saved `training_options.json`. There is only a Bool parameter `add_sr_module` , and a Int parameter `add_block` started with `add`.

In my downloaded code, I suppose this option is firstly passed through the `**synthesis_kwargs` in line 39 of the `DualTriPlaneGenerator` class in `training.dual_triplane.py`.

Then this option is passed to the `**synthesis_kwargs` in line 749 of the `Generator` class in `training.networks_stylegan2.py`.

Afterwards, it is passed to the `add_sr_module` in line 579 of the `SynthesisNetwork` class in `training.networks_stylegan2.py`. And this parameter controls whether there it is a 3D SR module.

Is this correct? Could you please kindly show me, where the `add_3dblock` is initially defined in the config files, or in the e.g. `main()` functions? And finally, which parameter, in which line controls whether the SR module is added?

Sincerely thanks for your kindly response😀

**Comment by SeanChenxy** [comment]
Hi, `retidx: [-3, -1]` will enable `add_3dblock`. 
https://github.com/SeanChenxy/Mimic3D/blob/77d313656df3cd5536d2c4c5766db3a56208eea6/training/networks_stylegan2.py#L598

**Comment by JiuTongBro** [comment]
Got it. Sincirely thanks for your kind responses.
