### ISSUE TITLE
Question about calculating PSNR-mv and SSIM-mv

### ISSUE THREAD

**Issue by hse1032** [SeanChenxy/Mimic3D#9]
Hi, Thanks for sharing the codebase of Mimic3D.

I have some questions about the procedure for calculating the PSNR and SSIM.

Papers (including Mimic3D and GRAM-HD) denote that they use 50 instances for calculating the PSNR and SSIM, 
and for each instance, they sample 30 mutiview images.
In such case, what camera poses are used for sampling the multiview images?
(e.g. randomly sampling the pose distribution?)

Thanks,

**Comment by hse1032** [comment]
I found the detailed explanation in the supplementary of GRAM-HD paper.

Sorry for bothering.

**Comment by seulqxq** [comment]
Hello, have you calculated PSNR and SSIM? Can you ask me how to achieve them, Can you provide the implementation method or code?

Thanks,

**Comment by hse1032** [comment]
I do not know the details about how the authors implement these metrics, as I think that it requires additional details to train the Neus.
What I found is just the experimental details in supp. of GRAM-HD, denoting they use 30 images uniformly sampled from -0.4 to 0.4 yaw radian for training Neus, and they use 50 instances to calculate the final score.

**Comment by seulqxq** [comment]
Thanks for your reply, I am trying to replicate the method of GRAM-HD, and now I am studying how to get the pose of the 50 instances of GRAM-HD.
